### ISSUE TITLE
No IE support?

### ISSUE THREAD

**Issue by MikeshCZ** [richardshepherd/Parallax-Scrolling#3]
Hello,

First of all I want to say big thank you for this simply and awesome tutorial.

But what I test it and it is totaly not working in IE (my version is 8). Is that true or what is going on? Only what I see is white background and standard formatted text.

Thank you for your help!

**Comment by dledet1** [comment]
Hi, I am wondering the same thing. Was the IE issue ever resolved?

**Comment by jrasmussen451** [comment]
Html5 shiv fixed it for me. Good luck!
